### PR TITLE
Update cypress

### PR DESCRIPTION
**Pull request by denar90**
* drop cypress-cli
* update cypress and use run it with chrome (finally we can cover our functionality by tests 🎉 ). P.S. I'm not sure if we have to install chrome manually on travis

### CODE REVIEW

**Comment by denar90** [comment]
Aaaaand test passes on a travis 💃 
image

**Comment by paulirish** [comment]
sweeet

**Comment by denar90** [comment]
really strange, CI for my fork passes (I even turned on debug mode for cypress) https://travis-ci.org/denar90/timeline-viewer
but for original repo it fails - https://travis-ci.org/ChromeDevTools/timeline-viewer
😞

**Comment by paulirish** [comment]
ah bummer. 
weird. :/

**Pull request merged**
