### PR TITLE
Add offline feature

### LINKED ISSUE #7: Make it works offline
It will be incredibly useful feature.
Load trace -> go offline -> refresh page -> still have data

---

 Since `timeline-viewer` site hosted with github (uses https) we can use service workers.

Thoughts?

P.S. I'd like to give it a shot 😃

### PR DESCRIPTION
**Pull request by denar90**
Added service worker generated by [sw-precache](https://github.com/GoogleChrome/sw-precache).

You can try in my fork - https://denar90.github.io/timeline-viewer/?loadTimelineFromURL=https://www.dropbox.com/s/s1n8m8n5oddgoxx/timeline-docs.json?dl=0

resolves #7

### CODE REVIEW

**Comment by denar90** [comment]
@paulirish do you wanna use smth else instead of `sw-precache`? Maybe just pure service-worker?

**Comment by paulirish** [comment]
This is pretty awesome. Just tried it out and its quite lovely.

A little concerned that caching all traces it opens will start chewing up disk space... but we can give it a shot.

I am happy using sw-precache. It keeps things much easier to maintain

However I do think we should expose something on the UI like... a little notification "This app now available offline" when the SW has finished populating the cache.

Once that's there, we can ship this. :)

**Comment by denar90** [comment]
Thanks for looking at it :) 
Really good point 👍 So, I'll take care about this stuff.

**Comment by denar90** [comment]
I've updated stuff and also pushed to my master, so you can play with it live.

**Comment by denar90** [comment]
P.S. Haven't tested with gdrive, just gist...

**Comment by denar90** [comment]
@paulirish do you know how can I test gDrive for my env? Can I somehow register stuff to integrate it with localhost?

**Comment by paulirish** [comment]
@denar90 heyo

here's a few URLs that should load if you auth to the viewer:

https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=drive://0BzvYe7bYFf--SzVwWG1zaWx5SEU
https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=drive://0BzvYe7bYFf--SkczdzJqb21nLVE
https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=drive://0BzvYe7bYFf--MjZuTjlyTmFpeUk

I just checked and the API key and Oauth settings were whitelisted for localhost:8000 but not 8080, which is now the port this is served on.
I added 8080, and also 8090 and 9999 just for fun.

http://localhost:8080/?loadTimelineFromURL=drive://0BzvYe7bYFf--MjZuTjlyTmFpeUk should be working any minute now.

**Comment by paulirish** [comment]
I also added https://denar90.github.io to the origin whitelist.

**Comment by paulirish** [comment]
okay as of just now http://localhost:8080/?loadTimelineFromURL=drive://0BzvYe7bYFf--MjZuTjlyTmFpeUk is loading for me. :)

**Comment by denar90** [comment]
thx 👍 
hehe, you just read my mind, right now I'm trying to setup apiKey/clientId to make it works ))))

**Comment by paulirish** [comment]
This is nice. Ideally I'd like to update the little online/offline banner with "all files cached" when the caching is complete.
But this could wait for another PR.

**Comment by paulirish** [comment]
> hehe, you just read my mind, right now I'm trying to setup apiKey/clientId to make it works ))))

You shouldn't have to. The API key origin updates takes like 5 minutes so i'm not seeing https://denar90.github.io/timeline-viewer/?loadTimelineFromURL=drive://0B4kGmGjUCQtIeWp2YWlYZTJOZE9NMXFQUENpSkZjUGRwdGpF working just yet but any minute now it should start.  no adjustments necessary on your side.

**Comment by paulirish** [comment]
FYI heres the api key origins

image

and the client id origins

image

**Comment by denar90** [comment]
cool 👍 thanks, this outh stuff a bit tricky :)

**Comment by paulirish** [comment]
yes. it's terrible. :)

**Comment by denar90** [comment]
It turned out that gdrive cors request is a bit tricky. It's not so simple to cache it, using `sw-toolbox`  , as gist files. I wanna add some service worker stuff for this, so it might take a time...

**Comment by paulirish** [comment]
okay.
maybe we can just pass through any googleapis/gdrive requests quickly?  i'm happy to have that part not work offline.

**Comment by denar90** [comment]
okay, so no offline support for gdrive files for now, just gists and dropbox...

I'll add final change for text offline/online badge  with phrase "all files cached" and it's ready to ✈️ 
Can also retry stuff one more time using my host to make sure we will not break current functionality? Maybe I missed smth...

**Comment by paulirish** [comment]
ya sg.

even tho we wont do offline for gdrive, i want to make sure the auth & dl flow for it isn't messed up. :)

 ill doublecheck this with ya

**Comment by denar90** [comment]
👍 
yeap, I'll cut them, just leave only source files and links to gist/dropbox.

**Comment by paulirish** [comment]
tested this out. seems good. let's roll with it!

**Comment by denar90** [comment]
COOL! 🎉 👯 💃
Was trying stuff about cached files notifications, but haven't finished yet... I'll make another pr though :)

**Pull request merged**
